workflows:
  cordova-android-build:
    name: Cordova Android Build
    max_build_duration: 60

    environment:
      node: 18
      groups:
        - android

    scripts:
      - npm install -g cordova
      - cordova platform add android@12.0.1
      - cordova requirements
      - cordova build android --release

    artifacts:
      - platforms/android/app/build/outputs/**/*.apk
      - platforms/android/app/build/outputs/**/*.aab
